### PR TITLE
Minor Update to Encourage Contributions

### PR DESCRIPTION
**Pull request by nelsonic**
+ adds [contributions welcome](https://github.com/docdis/learn-api-design/issues) badge.
+ adds golden ticket to intro & tidies quotes section

### CODE REVIEW

**Comment by nelsonic** [comment]
@besarthoxhaj have you had a chance to review this? :wink:

**Comment by besarthoxhaj** [comment]
Will have a look right now!! @nelsonic :)

**Comment by besarthoxhaj** [comment]
@nelsonic this is lots of useful material! I'm already going through all the videos and readings I can! Love it!:)

**Comment by nelsonic** [comment]
@besarthoxhaj lol. its just a *starting point*. 
any questions before you can merge the PR? :wink:

**Comment by besarthoxhaj** [comment]
I don't feel prepared enough to contribute yet. However so far I simply love it! Will merge it now!

**Comment by nelsonic** [comment]
thanks @besarthoxhaj :+1:

**Pull request merged**
